version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependency scanning tools..."
      - npm install -g npm-audit-resolver snyk
      - echo "Authenticating with Snyk..."
      - snyk auth 8e4f1d25-4bc5-42ca-8500-b02f1e77e166

  pre_build:
    commands:
      - echo "Running dependency vulnerability scans..."
      - npm audit --json > audit-results.json || true
      - snyk test --severity-threshold=high || true

  build:
    commands:
      - echo "Analyzing scan results..."
      - node analyze-audit.js # Script to fail the build if critical issues exist.

  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files:
    - audit-results.json
