version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase jjj"
      - npm install

  build:
    commands:
      - echo "Build phase kkkk"
      - npm run build

      # Additional build commands if needed

artifacts:
  files:
    - '**/*'
 # base-directory: dist
